version: '3.8'

services:
  service-account:
    depends_on: 
      - db-postgresql
    build:
      context: .
    container_name: account-service
    hostname: host-account-service
    networks:
      - microservices-network
    ports:
      - 8080:8080
      - 443:443
    environment:
      - PGUSER=${PGUSER:-mikhailgorbachev666}
      - PGPASSWORD=${PGPASSWORD:?database password not set}
      - PGHOST=${PGHOST:-host-db-postgresql}
      - PGPORT=${PGPORT:-5432}
      - PGDATABASE=${PGDATABASE:-db_service_account}
    deploy:
      restart_policy:
        condition: on-failure
  
  db-postgresql:
    image: postgres:latest
    restart: always
    container_name: db-postgresql
    hostname: host-db-postgresql
    networks:
      - microservices-network
    ports:
      - 5432:5432
    volumes:
      - volume-db-postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_INITDB_ARGS=${POSTGRES_INITDB_ARGS:-}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?database password not set}
      - POSTGRES_USER=${POSTGRES_USER:-mikhailgorbachev666}
      - POSTGRES_DB=${POSTGRES_DB:-db_service_account}
      - PGDATA=${PGDATA:-/var/lib/postgresql/data/pgdata}
    #command: start-single-node --insecure

volumes:
  volume-db-postgresql:

networks:
  microservices-network:
    driver: bridge