# This is a basic workflow to help you get started with Actions

name: Run CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Use to fix error on 'Build Docker image' step.
      # Error: buildx failed with: error: failed to solve: invalid reference format: repository name must be lowercase
      # https://github.community/t/github-actions-repository-name-must-be-lowercase/184924
      - name: Set repository.name name to lowercase 
        run: |
          echo "REPOSITORY_NAME_LC=${REPOSITORY_NAME,,}" >>${GITHUB_ENV}
          echo "REPOSITORY_LC=${REPOSITORY,,}" >>${GITHUB_ENV}
        env:
          REPOSITORY_NAME: '${{ github.event.repository.name }}'
          REPOSITORY: '${{ github.repository }}'

      - name: Set up Docker Buildx
        id:   buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.2

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch required Go modules
        run:  go mod download

      - name: Build
        run:  go build -v ./...

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with: 
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          load: true
          tags: ${{ env.REPOSITORY_NAME_LC }}:latest, ${{ env.REPOSITORY_LC }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Run functional tests
        run: go test -v ./...